function addUI(w,d){
 if(d.getElementById('tab-cooperation'))return;
 const nav=d.getElementById('mainNav');if(nav){const b=d.createElement('button');b.className='nb';b.dataset.tab='cooperation';b.textContent='🤝 Cooperação';const s=nav.querySelector('[data-tab="scoreboard"]');nav.insertBefore(b,s||null);b.onclick=()=>{w.switchTab('cooperation');openCoop(w,d)}}
 const mm=d.querySelector('.mm-inner');if(mm){const b=d.createElement('button');b.className='mm-btn';b.dataset.tab='cooperation';b.textContent='🤝 Cooperação';const s=mm.querySelector('[data-tab="scoreboard"]');mm.insertBefore(b,s||null);b.onclick=()=>{w.switchTab('cooperation');openCoop(w,d)}}
 const sec=d.createElement('section');sec.id='tab-cooperation';sec.className='tab';sec.innerHTML=`
 <div class="c7hero"><div class="c7kick">BANCO DE CONEXÕES CIENTÍFICAS • CLUSTER 7</div><h2>Encontre a pessoa certa e já saiba como conectar.</h2><p>Perfis dos PPGs parceiros com minibio, competências, contato público quando disponível e um motor para montar equipes complementares.</p><div class="c7metrics"><div class="c7metric"><b id="c7Total">—</b><span>docentes</span></div><div class="c7metric"><b id="c7PPGs">—</b><span>PPGs</span></div><div class="c7metric"><b id="c7Profiles">—</b><span>minibios prontas</span></div><div class="c7metric"><b id="c7Contacts">—</b><span>contatos públicos</span></div></div></div>
 <div class="c7builder"><h3>🧩 Montar uma cooperação</h3><div class="c7sub">Descreva o problema e a lacuna. O sistema procura complementaridade entre os programas; o resultado indica aderência, não disponibilidade confirmada.</div><div class="c7modes"><button class="c7mode on" data-mode="research">🔬 Tenho uma pesquisa<span>Cole o problema ou resumo.</span></button><button class="c7mode" data-mode="person">🎯 Preciso de alguém que…<span>Procure uma competência específica.</span></button><button class="c7mode" data-mode="action">🚀 Quero criar uma ação<span>Monte equipe para produto concreto.</span></button></div><div class="c7form"><div class="c7field full"><label id="c7BriefLabel">Projeto / problema científico</label><textarea id="c7Brief" placeholder="Ex.: calor, qualidade do ar e saúde no Pantanal..."></textarea></div><div class="c7field"><label>O que meu grupo já domina</label><input id="c7Have" placeholder="Ex.: clima, estatística, MP2,5"></div><div class="c7field"><label>O que preciso fortalecer</label><input id="c7Need" placeholder="Ex.: dispersão, saúde, redes neurais"></div><div class="c7field"><label>PPG de origem</label><select id="c7Origin"><option value="">Não informar</option></select></div><div class="c7field"><label>Tipo de cooperação</label><select id="c7Action"><option value="coorientacao">Coorientação</option><option value="projeto">Projeto multicêntrico / edital</option><option value="artigo">Artigo / revisão em rede</option><option value="banca">Banca / qualificação</option><option value="disciplina">Disciplina compartilhada</option><option value="mobilidade">Mobilidade / visitante</option><option value="dados">Dados / infraestrutura / campo</option></select></div></div><button class="c7find" id="c7Find">Encontrar parceiros</button></div>
 <div class="c7match" id="c7Match"><div class="c7summary" id="c7Summary"></div><div class="c7matchgrid" id="c7MatchGrid"></div><div class="c7team" id="c7Team"><h4>Equipe selecionada</h4><div class="c7teamchips" id="c7TeamChips"></div><div class="c7teambtns"><button class="go" id="c7Proposal">🚀 Criar proposta no Cluster</button><button id="c7Clear">Limpar seleção</button></div></div></div>
 <div class="c7head"><h3>Docentes prontos para conectar</h3><div class="c7count" id="c7Count"></div></div><div class="c7tools"><input id="c7Search" placeholder="🔎 Nome, tema, método, contato..."><select id="c7Program"><option value="">Todos os PPGs</option></select><select id="c7Status"><option value="">Todos os vínculos</option><option value="permanente">Permanente</option><option value="docente">Docente</option><option value="colaborador">Colaborador</option><option value="associado">Associado</option></select></div><div class="c7chips" id="c7Chips"></div><div class="c7grid" id="c7Grid"><div class="c7no">Carregando...</div></div>`;
 d.querySelector('main').appendChild(sec);
 sec.querySelectorAll('.c7mode').forEach(b=>b.onclick=()=>setMode(d,b));
 d.getElementById('c7Find').onclick=()=>runMatch(w,d);
 d.getElementById('c7Search').oninput=()=>renderBank(d);d.getElementById('c7Program').onchange=()=>renderBank(d);d.getElementById('c7Status').onchange=()=>renderBank(d);
 d.getElementById('c7Clear').onclick=()=>{c7Team=[];renderTeam(d);renderMatches(d);renderBank(d)};
 d.getElementById('c7Proposal').onclick=()=>createProposal(w,d);
}
function setMode(d,b){d.querySelectorAll('.c7mode').forEach(x=>x.classList.toggle('on',x===b));const m=b.dataset.mode,L=d.getElementById('c7BriefLabel'),T=d.getElementById('c7Brief');if(m==='research'){L.textContent='Projeto / problema científico';T.placeholder='Ex.: calor, qualidade do ar e saúde no Pantanal...'}else if(m==='person'){L.textContent='Quem / competência que você precisa';T.placeholder='Ex.: alguém que trabalhe com microplásticos e contaminantes...'}else{L.textContent='Ação que você quer montar';T.placeholder='Ex.: artigo comparativo sobre qualidade da água em três regiões...'}}
async function openCoop(w,d){try{await loadData();setup(d);renderBank(d)}catch(e){d.getElementById('c7Grid').innerHTML='<div class="c7no">Não foi possível carregar o banco.</div>'}}
function setup(d){
 if(d.getElementById('c7Program').dataset.ready)return;d.getElementById('c7Program').dataset.ready='1';
 const ps=(c7Base.programas||[]).map(p=>({key:p.ppg+'|'+p.ies,label:p.ppg+' • '+p.ies,n:(p.docentes||[]).length}));
 const sel=d.getElementById('c7Program'),org=d.getElementById('c7Origin'),chips=d.getElementById('c7Chips');
 sel.innerHTML='<option value="">Todos os PPGs</option>'+ps.map(p=>`<option value="${esc(p.key)}">${esc(p.label)} (${p.n})</option>`).join('');org.innerHTML='<option value="">Não informar</option>'+ps.map(p=>`<option value="${esc(p.key)}">${esc(p.label)}</option>`).join('');chips.innerHTML='<button class="c7chip on" data-p="">TODOS <b>'+c7People.length+'</b></button>'+ps.map(p=>`<button class="c7chip" data-p="${esc(p.key)}">${esc(p.label)} <b>${p.n}</b></button>`).join('');chips.querySelectorAll('.c7chip').forEach(b=>b.onclick=()=>{sel.value=b.dataset.p;renderBank(d)});
 d.getElementById('c7Total').textContent=c7People.length;d.getElementById('c7PPGs').textContent=ps.length;d.getElementById('c7Profiles').textContent=c7People.filter(x=>x.bio).length;d.getElementById('c7Contacts').textContent=c7People.filter(x=>x.contact).length;
}
function contactHtml(p){const label=p.contactType==='programa'?'Contato oficial do programa':'Contato público';return p.contact?`<div class="c7contact"><b>${label}</b><div class="c7mail">📧 ${esc(p.contact)}</div></div>`:`<div class="c7contact"><b>Contato</b><div class="c7no">Ainda não localizado em fonte pública individual.</div></div>`}
function cardHtml(p,score,why){const on=c7Team.includes(p.name);return `<article class="c7card">${score!=null?`<div class="c7score">${score}/100</div>`:`<div class="c7status">${esc(p.status)}</div>`}<div class="c7top"><div class="c7av">${esc(initials(p.name))}</div><div><div class="c7name">${esc(p.name)}</div><div class="c7inst">${esc(p.ppg)} • ${esc(p.ies)}</div></div></div><div class="c7bio">${esc(bioAuto(p))}</div>${p.area?`<div class="c7skills"><b>Competências:</b> ${esc(p.area)}</div>`:''}${p.linha?`<div class="c7skills"><b>Linha:</b> ${esc(p.linha)}</div>`:''}${why?`<div class="c7why"><b>Por que combina:</b> ${esc(why)}</div>`:''}${contactHtml(p)}<div class="c7actions"><button class="c7btn primary ${on?'on':''}" data-pick="${esc(p.name)}">${on?'✓ Na equipe':'🤝 Selecionar'}</button>${p.fonte?`<a class="c7source" href="${esc(p.fonte)}" target="_blank" rel="noopener">↗ fonte oficial</a>`:''}</div></article>`}
function bindPicks(d,root){root.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{const n=b.dataset.pick;c7Team=c7Team.includes(n)?c7Team.filter(x=>x!==n):[...c7Team,n];renderTeam(d);renderMatches(d);renderBank(d)})}
function renderBank(d){if(!c7Base)return;const q=norm(d.getElementById('c7Search').value),pk=d.getElementById('c7Program').value,st=d.getElementById('c7Status').value;d.querySelectorAll('.c7chip').forEach(b=>b.classList.toggle('on',b.dataset.p===pk));const rows=c7People.filter(x=>(!pk||x.ppg+'|'+x.ies===pk)&&(!st||x.status===st)&&(!q||norm([x.name,x.ppg,x.ies,x.status,x.area,x.linha,x.bio,x.contact].join(' ')).includes(q)));d.getElementById('c7Count').textContent=rows.length+' resultado'+(rows.length===1?'':'s');const g=d.getElementById('c7Grid');g.innerHTML=rows.length?rows.map(x=>cardHtml(x,null,'')).join(''):'<div class="c7no">Nenhum docente encontrado.</div>';bindPicks(d,g)}
